apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zradirani
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: zradirani
    newName: rg.fr-par.scw.cloud/djnd/zradirani
    newTag: '0fa02b3875499dfcd0dd0b034879a90be6a23dc5'