apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zradirani
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: zradirani
    newName: rg.fr-par.scw.cloud/djnd/zradirani
    newTag: 'b7c6a5754dc8ce37aae06cc349d49aa27a29250e'