apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: botri-sovrastva
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: botri-sovrastva
    newName: rg.fr-par.scw.cloud/djnd/botri-sovrastva
    newTag: 'ccc0d20443be22c803b340d7971f4297d168475f'
